### ISSUE TITLE
Git fat pull aborts when using together with sparse-checkout

### ISSUE THREAD

**Issue by demonyangyue** [cyaninc/git-fat#49]
Hi,

I am using `git fat pull` in a repository which uses sparse-checkout to have only specific folders in working directory. I get the following exception:

```
Traceback (most recent call last):
  File "/usr/local/bin/git-fat", line 1150, in <module>
    main()
  File "/usr/local/bin/git-fat", line 1139, in main
    run(backend, **kwargs)
  File "/usr/local/bin/git-fat", line 1018, in run
    getattr(gitfat, fn)(**kwargs)
  File "/usr/local/bin/git-fat", line 926, in pull
    self.checkout()
  File "/usr/local/bin/git-fat", line 870, in checkout
    for digest, fname in self._orphan_files():
  File "/usr/local/bin/git-fat", line 623, in _orphan_files
    st = os.lstat(fname)
OSError: [Errno 2] No such file or directory: ...
```

I think the root cause is: when using sparse checkout, some files exist in index may not exits in working directory, which makes `os.lstat(fname)` throw the exception.

Will submit a pull request later.

**Comment by abraithwaite** [comment]
This resolves #12 as well.  As for why it wasn't done to begin with, I'm not sure.  I think there was a reason, but of course I didn't write it down.  I'm going to play with this a bit and make a test before merging.

Thanks!
