### ISSUE TITLE
subprocess WindowsError on git-fat push

### ISSUE THREAD

**Issue by couplewavylines** [cyaninc/git-fat#59]
On Windows, using Python 2.7.10 64-bit and git-fat 0.5.0 installed from pypi.  I get an exception when I attempt a "git-fat push"

```
$ git-fat push
Traceback (most recent call last):
  File "c:/Python27/Scripts/git-fat", line 1121, in <module>
    main()
  File "c:/Python27/Scripts/git-fat", line 1110, in main
    run(backend, **kwargs)
  File "c:/Python27/Scripts/git-fat", line 991, in run
    getattr(gitfat, fn)(**kwargs)
  File "c:/Python27/Scripts/git-fat", line 905, in push
    files = self._referenced_objects(**kwargs) & self._cached_objects()
  File "c:/Python27/Scripts/git-fat", line 535, in _referenced_objects
    objs_dict = self._managed_files(**kwargs)
  File "c:/Python27/Scripts/git-fat", line 593, in _managed_files
    for objhash, objtype, size in revlistgen:
  File "c:/Python27/Scripts/git-fat", line 557, in _rev_list
    awk = sub.Popen([awk_tool, '{print $1}'], stdin=revlist.stdout, stdout=sub.PIPE)
  File "c:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "c:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

I then ran it with PDB, and it pointed here right after the uncaught exception, in subprocess.py line 977:

```
972                     if p2cread is not None:
973                         _close_in_parent(p2cread)
974                     if c2pwrite is not None:
975                         _close_in_parent(c2pwrite)
976                     if errwrite is not None:
977  ->                     _close_in_parent(errwrite)
978
979                 # Retain the process handle, but close the thread handle
980                 self._child_created = True
981                 self._handle = hp
982                 self.pid = pid
(Pdb) p errwrite
<_subprocess_handle object at 0x00000000022C52A0>
(Pdb)
```

**Comment by cztomczak** [comment]
This is yet todo to provide 64-bit windows package on PyPI. What you've installed currently is Linux/Mac source package (.tar.gz).

**Comment by couplewavylines** [comment]
I see. It worked after I switched over to 32-bit Python, which is fine for my purpose. Thank you!

**Comment by mikofski** [comment]
high, I've put a bitness independent version of gitfat here: https://dl.dropboxusercontent.com/u/19049582/git_fat-0.5.0-main.zip. install it with pip

```
pip install git_fat-0.5.0-main.zip
```

details are on my post here http://poquitopicante.blogspot.com/2015/04/git-big-media-on-windows.html

I will try to send a pull request one day because I did a few things slightly different. Works for both MSYS GitBash and Windows CMD.
